server:
  port: 8082
  address: 0.0.0.0
  tomcat:
    basedir: ./
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: inspector
  freemarker:
    suffix: .ftl
    cache: false
  datasource:
    url: jdbc:mariadb://localhost:3306/inspector?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: "newPassword1234"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
mail:
  host: smtp.gmail.com
  port: 587
  username: senderinquiry@gmail.com
  password: "jwwd djdm gyxj hlnx"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

